language: node_js
node_js:
  - 10.13.0
cache:
  directories:
    - node_modules
deploy:
  provider: heroku
  api_key:
    secure: PmziNjXzq1az/vsTVcB5ITnq4WSAUjwwWaM/FsTFyjLiNtZTb0vabHDA7fitV9KKLEsMTFwmnput17FvJ6AoPUuDISfCVz6dQn2yJwr38Z4MkrvUs7QhQmchpaskC99CNysrG1X7SddY6ZYASxplhrbvfK0VclPKW66KeoGq0MhzPjjEKl9yf/oA2Nt1ZwuEJEYtlH3thnYvEsj3aCSpLR/kA0PoAASjQn2vT3X4DSfmNxIvNU3cHGrh43QmKY00aOM+xGv6QL43bDEb7oDTgr4J5pyCs7w5QGnAZjAHW4zc075PzNKZAe4uyu703KJ4ZvGvGgsvOh2FejiBjUCYIDx35Il5PvcuAms2ww9WMtJwbU1bu7gm1tiDeFwZz/PxvqoKeh0LJeTPIkAhULrAEnCCDE7pQma5MlwYpyTWZVBmaeV9v4sZML9eOI9/ujdJXRgBnrc5QIAN4osrL68n4NmlbjBACjQ27FiD1YsQim4ZYwECrTdYWhcJj45A9+PoIqpGyjCUCFWgIvsaDmZYYNbEgw1kJ0ZHnSL5945SGfU2MYCDUfM4hOCCD4v7uJLuyfD+Nj2xXUX/57+raH7fjnwntPvdLE0/XyoI6y8mXvJ87ZcOVzQ3CtViiujrdPHuUN5XNTpupdWPF7mEM42asK56ONFbIdX373ZRBDHza1c=
  project-name: playthru
  app: playthru
