language: node_js
node_js:
  - 10.13.0
cache:
  directories:
    - node_modules
before_install:
  - echo -e "machine api.heroku.com\n  login jackbittiner@hotmail.com\n  password $CI_USER_PASSWORD" > ~/.netrc
deploy:
  provider: script
  script: bash deploy.sh
  skip-cleanup: true
